// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjrCx6C0l_RDDw4rFjac2sfbklT_qI8YQ',
    appId: '1:206670593554:web:31ef0bee48769d3995e2cb',
    messagingSenderId: '206670593554',
    projectId: 'craftconnect-20fa6',
    authDomain: 'craftconnect-20fa6.firebaseapp.com',
    storageBucket: 'craftconnect-20fa6.firebasestorage.app',
    measurementId: 'G-6JQ7W5TR27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCtvcUjs_7x_pIBUUG7rfqpgWWEcY5RvM',
    appId: '1:206670593554:android:92e391fac31b407995e2cb',
    messagingSenderId: '206670593554',
    projectId: 'craftconnect-20fa6',
    storageBucket: 'craftconnect-20fa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiuSN-RXjlNZNbWIHQBL6a7wXZI2ZsMQw',
    appId: '1:206670593554:ios:3ce46784fe87a5ed95e2cb',
    messagingSenderId: '206670593554',
    projectId: 'craftconnect-20fa6',
    storageBucket: 'craftconnect-20fa6.firebasestorage.app',
    iosBundleId: 'com.example.craftconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiuSN-RXjlNZNbWIHQBL6a7wXZI2ZsMQw',
    appId: '1:206670593554:ios:3ce46784fe87a5ed95e2cb',
    messagingSenderId: '206670593554',
    projectId: 'craftconnect-20fa6',
    storageBucket: 'craftconnect-20fa6.firebasestorage.app',
    iosBundleId: 'com.example.craftconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjrCx6C0l_RDDw4rFjac2sfbklT_qI8YQ',
    appId: '1:206670593554:web:03d76f9871063ceb95e2cb',
    messagingSenderId: '206670593554',
    projectId: 'craftconnect-20fa6',
    authDomain: 'craftconnect-20fa6.firebaseapp.com',
    storageBucket: 'craftconnect-20fa6.firebasestorage.app',
    measurementId: 'G-JVHLRK077S',
  );

}